auth-ballerina/src/auth/invocation_context.bal

Remove public keyword from function params

---

.github/workflows/build-master.yml
README.md
auth-ballerina/build.gradle

This PR updates the readme of the repository with the required configurations to run `./gradlew test` command.

Update readme and configurations

---

auth-ballerina/src/auth/inbound_auth_provider.bal
auth-ballerina/src/auth/inbound_basic_auth_provider.bal
auth-ballerina/src/auth/invocation_context.bal
auth-ballerina/src/auth/outbound_auth_provider.bal
auth-ballerina/src/auth/outbound_basic_auth_provider.bal

Fix auth module for object syntax change

---

auth-native/src/main/java/org/ballerinalang/stdlib/auth/GetInvocationContext.java

Migrate jBallerina Runtime APIs

---

.github/workflows/pull-request.yml
auth-ballerina/src/auth/auth_errors.bal
auth-ballerina/src/auth/inbound_auth_provider.bal
auth-ballerina/src/auth/inbound_basic_auth_provider.bal
auth-ballerina/src/auth/invocation_context.bal
auth-ballerina/src/auth/outbound_auth_provider.bal
auth-ballerina/src/auth/outbound_basic_auth_provider.bal
auth-ballerina/src/auth/utils.bal
auth-native/src/main/java/org/ballerinalang/stdlib/auth/GetInvocationContext.java

Update auth module with isolated functions

---

auth-ballerina/src/auth/auth_errors.bal
auth-ballerina/src/auth/inbound_auth_provider.bal
auth-ballerina/src/auth/inbound_basic_auth_provider.bal
auth-ballerina/src/auth/outbound_auth_provider.bal
auth-ballerina/src/auth/outbound_basic_auth_provider.bal
auth-ballerina/src/auth/utils.bal

Revert making auth functions as isolated

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
auth-ballerina/build.gradle
build.gradle

Update GitHub release workflow

---

.github/workflows/build-master.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
README.md
auth-ballerina/Ballerina.toml
auth-native/src/main/java/module-info.java

Migrate to JDK11

---

auth-native/build.gradle
auth-native/src/main/java/org/ballerinalang/stdlib/auth/GetInvocationContext.java
build.gradle
gradle.properties

Enable checkstyle and spotbugs

---

auth-native/src/main/java/module-info.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/Constants.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/GetInvocationContext.java

Refactor ballerina runtime api usages

Migrate ballerina runtime apis

---

auth-ballerina/src/auth/outbound_basic_auth_provider.bal
auth-ballerina/src/auth/utils.bal
gradle.properties

Update log API usages and dependencies list

---

auth-ballerina/Ballerina.toml
auth-ballerina/build.gradle
build.gradle

Update dependency order

---

auth-ballerina/build.gradle

$subject related to https://github.com/ballerina-platform/module-ballerina-auth/pull/35

Exclude adding file pattern to cache

---

auth-ballerina/build.gradle

Enable copying of dependency caches and doc generation

---

build.gradle
gradle.properties

Add runtime transitive dependency

---

auth-ballerina/build.gradle
build.gradle

Refactor gradle configurations

---

.gitignore

Add secrets path to gitignore

---

auth-ballerina/auth_errors.bal
auth-ballerina/outbound_basic_auth_provider.bal
auth-ballerina/utils.bal

Update for log API changes

---

auth-ballerina/init.bal
auth-native/src/main/java/org/ballerinalang/stdlib/auth/Constants.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/GetInvocationContext.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ModuleUtils.java

Replace hard coded native package version

---

build.gradle
gradle.properties

Rename system module dependency as os module

---

auth-ballerina/auth_errors.bal
auth-ballerina/auth_utils.bal
auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal

Fix for syntax changes related to errors

---

auth-ballerina/Ballerina.toml
auth-ballerina/auth_utils.bal
auth-ballerina/build.gradle
build.gradle
gradle.properties

Replace usages of stringutils APIs

---

auth-ballerina/build.gradle

Update ballerina command to bal command

---

auth-ballerina/Package.md

Update package md files

---

auth-ballerina/init.bal
auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal

Related Issue: https://github.com/ballerina-platform/ballerina-lang/issues/28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training …

Change the name of the `java` langlib module to `jballerina.java`

---

auth-ballerina/Ballerina.toml
auth-ballerina/Dependencies.toml
auth-ballerina/build.gradle

Fixes ballerina-platform/ballerina-lang#27988

Add Dependencies.toml

---

README.md
auth-ballerina/auth_constants.bal
auth-ballerina/auth_errors.bal
auth-ballerina/client_basic_auth_provider.bal
auth-ballerina/listener_file_user_store_basic_auth_provider.bal
auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal

Update ballerina documentations

---

auth-ballerina/build.gradle

Revert dependency toml file after build

---

auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal

Fix LDAP config for camel case

---

auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/LdapConstants.java

Fix a bug in LDAP user store provider

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
auth-ballerina/build.gradle

Publish code coverage exec file as a maven artifact

---

auth-ballerina/build.gradle

Refactor build task order

---

auth-ballerina/build.gradle

Avoid running tests twice when publishing

---

README.md
auth-ballerina/Package.md

Update docs for swan-lake URL change

---

.github/workflows/pull-request.yml
auth-ballerina/build.gradle
auth-ballerina/listener_file_user_store_basic_auth_provider.bal
auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal
auth-ballerina/tests/listener_ldap_user_store_basic_auth_provider_test.bal
auth-ballerina/tests/resources/openldap/bootstrap.ldif
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/Authenticate.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/GetGroups.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/InitLdapConnection.java

Add unit tests for authentication with LDAP user store

---

.github/workflows/publish-release.yml
auth-ballerina/build.gradle
build.gradle
gradle.properties

- Subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/957
- Bump the next version to a minor alpha version
- Improve the build scripts and actions to publish the artifacts to the Ballerina central during a release

Enable publishing to Ballerina Central during release

---

auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/SslTrustConfig.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/Authenticate.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/GetGroups.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/InitLdapConnection.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/utils/LdapUtils.java

Refactor debug logs

---

auth-ballerina/build.gradle
build.gradle

Re-order build tasks to publish to ballerina central

---

auth-ballerina/build.gradle

$subject for https://github.com/ballerina-platform/module-ballerina-auth/pull/94

Update missing configurations

---

README.md
auth-ballerina/build.gradle

Refactor readme and build.gradle

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
auth-ballerina/build.gradle

Remove publishing exec artifacts and archiving test json

---

auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal
auth-ballerina/tests/listener_ldap_user_store_basic_auth_provider_test.bal
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/CommonLdapConfiguration.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/ConnectionContext.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/LdapConstants.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/InitLdapConnection.java

$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/967

Update fields representing time-units with the convention

---

auth-ballerina/build.gradle

> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763

Add extracted bala in the zip artifact

---

auth-ballerina/Package.md

$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1376

Update Package.md for BBE update

---

auth-ballerina/build.gradle

> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032

Add -c flag to build command

---

auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/LdapConstants.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/InitLdapConnection.java

Update SecureSocket API of LDAP

---

auth-ballerina/auth_utils.bal

This PR remove the `checkpanic` keyword usages for type narrowing.

Remove usages of checkpanic for type narrowing

---

auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/CommonLdapConfiguration.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/Authenticate.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/GetGroups.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/nativeimpl/InitLdapConnection.java
auth-native/src/main/java/org/ballerinalang/stdlib/auth/ldap/utils/LdapUtils.java
changelog.md

$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1242

Improve error messages and log messages

---

auth-ballerina/build.gradle
build.gradle

Strip stdlib dependency version

---

auth-ballerina/build.gradle

Fix publishing workflow

---

auth-ballerina/build.gradle

Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381

Set flag to enable Jacoco Coverage XML generation

---

.github/workflows/pull-request.yml
auth-ballerina/build.gradle

Skip Docker based tests in Windows OS

---

README.md
auth-ballerina/Module.md
auth-ballerina/Package.md
auth-ballerina/auth_errors.bal
auth-ballerina/auth_utils.bal
auth-ballerina/client_basic_auth_provider.bal
auth-ballerina/listener_basic_auth_provider.bal
auth-ballerina/listener_file_user_store_basic_auth_provider.bal
auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal
auth-ballerina/tests/test_utils.bal

Improve the API documentation and markdown files

---

auth-ballerina/build.gradle

$subject
Related to https://github.com/ballerina-platform/module-ballerina-auth/pull/197

Fix a bug in gradle task order

---

auth-ballerina/Module.md
auth-ballerina/client_basic_auth_provider.bal
auth-ballerina/listener_ldap_user_store_basic_auth_provider.bal

Improve API docs

---

auth-ballerina/Package.md

This is a part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1462

Update Package.md links into HTML format

---

README.md
auth-ballerina/Module.md
auth-ballerina/Package.md

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1550

Improve documentation

---

ballerina/listener_file_user_store_basic_auth_provider.bal

Add error message for validating file user store values

---

docs/spec/spec.md

Add specification for `ballerina/auth` library.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2207

Add auth library specification

---

ballerina/Package.md

Review the 'auth' module 'Package.MD' description.

Review the 'auth' Module 'Package.MD' Description

---

ballerina/Module.md

Review the 'auth' module description.

Review the 'auth' Module Description

---

README.md

Review the 'auth' Module 'Readme.MD' description.

Review the 'auth' Module 'Readme.MD' Description

---

ballerina/auth_errors.bal
ballerina/auth_utils.bal
ballerina/client_basic_auth_provider.bal
ballerina/listener_file_user_store_basic_auth_provider.bal
ballerina/listener_ldap_user_store_basic_auth_provider.bal
ballerina/tests/auth_utils_test.bal
ballerina/tests/client_basic_auth_provider_test.bal
ballerina/tests/listener_file_user_store_basic_auth_provider_test.bal
ballerina/tests/listener_ldap_user_store_basic_auth_provider_test.bal
ballerina/tests/test_utils.bal
native/src/main/java/io/ballerina/stdlib/auth/ldap/SslContextTrustManager.java

$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2146

Refactor code base

---

.github/workflows/pull-request.yml
ballerina/tests/Config.toml
ballerina/tests/auth_utils_test.bal
ballerina/tests/listener_file_user_store_basic_auth_provider_test.bal

$subject fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2148

Improve unit tests with negative tests

---

ballerina/auth_errors.bal

$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3026
N/A

Convert error logs to debug logs

---

ballerina/Ballerina.toml
build-config/resources/Ballerina.toml

> $Subject
> Related to [`Add details for native jars used in the standard library #3117`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3117)
N/A

Update native jar

---

.github/workflows/update-spec.yml

$subject
Related to [#3154](https://github.com/ballerina-platform/ballerina-standard-library/issues/3154)

Add stdlib specs update workflow

---

docs/spec/spec.md

Fix Inconsistencies in Auth Spec

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties
native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/auth-native/reflect-config.json

Fixes: [#3415](https://github.com/ballerina-platform/ballerina-standard-library/issues/3415)

Add native image build configurations

---

docs/spec/spec.md

Fix a Typo in the Spec

---

README.md
ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/Package.md
build-config/resources/Ballerina.toml
changelog.md
docs/spec/spec.md
gradle.properties

>$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3463

Replace Slack Channel Link and Update Dependent Module Versions

---

gradle.properties

Update version of cache

---

.github/workflows/update-spec.yml

Fix spec workflow path

---

docs/spec/spec.md

Fixes: [#3774](https://github.com/ballerina-platform/ballerina-standard-library/issues/3774)
N/A

Fix Formatting in the Spec

---

native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/auth-native/reflect-config.json

>$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3755
N/A

Add missing native-image configs

---

.github/workflows/pull-request.yml

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3988

Add Codecov Upload Retry Step

---

ballerina/Dependencies.toml
gradle.properties

Update lang timestamp version

---

.github/workflows/process-load-test-result.yml
.github/workflows/pull-request.yml
.github/workflows/trigger-load-tests.yml
ballerina/Ballerina.toml
ballerina/Dependencies.toml

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4098

 Add codecov token to pr build workflow and add workflow calls to load tests

---

.github/workflows/pull-request.yml

>$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4221

Introduce Concurrency Setting for PR Build

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update Dependency Version

---

examples/order-management-service/README.md

Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4378
N/A

Update Meta Information in Examples

---

.github/workflows/build-with-bal-test-native.yml

>$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/4142
N/A

Add GraalVM Check for the PRs

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/auth_utils.bal
build.gradle
gradle.properties

>$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4382
N/A

Remove Regex Package Usages

---

load-tests/order_management_service/src/Cloud.toml

>$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4414

Temporarily Increase the load-test Reources

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

Update Dependency Versions

---

.github/workflows/build-with-bal-test-graalvm.yml
README.md
ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

>$subject
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4548
N/A

 Incorporate Native Build Command Change

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
build-config/checkstyle/build.gradle
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle

Migrate to Java 17

---

gradle.properties
spotbugs-exclude.xml

Fix spotbugs issues and update ballerina gradle plugin version

---

gradle.properties

Update log version to the latest time-stamp version

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Bump to the Next Minor Version and Update the Distribution

---

.github/workflows/build-with-bal-test-graalvm.yml

>$subject
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4787

Add GraalVM Check for '2201.7.x' branch

---

ballerina/Dependencies.toml
ballerina/build.gradle

Fixes: [#4021](https://github.com/ballerina-platform/ballerina-standard-library/issues/4021)

Optimize Build Script to Skip Docker Tasks when Using the -x test Flag 

---

.github/workflows/pull-request.yml

Inherit Secrets in Pull Request Workflows

---

.github/workflows/build-timestamped-master.yml

Update the Build Workflow

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update the Distribution Version to 2201.9.0

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/build.gradle
ballerina/tests/resources/openldap/compose.yml

Update Docker Command to Docker Compose v2

---

ballerina/Dependencies.toml
ballerina/build.gradle
ballerina/tests/resources/openldap/compose.yml

[2201.8.x] Update Docker Command to Docker Compose v2

---

ballerina/build.gradle
ballerina/tests/resources/openldap/compose.yml

[2201.7.x] Update docker command to docker compose v2

---

gradle.properties

Update ballerina gradle-plugin version

---

ballerina/Dependencies.toml
ballerina/build.gradle
ballerina/tests/resources/openldap/compose.yml
gradle.properties

Update gradle plugin version

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

[2201.9.x] Update Module Version

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Update Dependency Versions for U11

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

Update library timestamp dependencies
